## 构造神经网络

### 5.2 Pytorch nn模块 

In [34]:
import torch.nn as nn
import torch
from torch import optim

In [22]:
linear_model = nn.Linear(2, 1) # 1 input, 1 output

In [31]:
input = torch.tensor([[1.0, 2.0],[1.0, 2.0],[1.0, 2.0]])
print(input.shape)
linear_model(input)

torch.Size([3, 2])


tensor([[0.7272],
        [0.7272],
        [0.7272]], grad_fn=<AddmmBackward0>)

In [32]:
input = torch.ones(20, 2)
print(input.shape)
linear_model(input)

torch.Size([20, 2])


tensor([[0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859],
        [0.1859]], grad_fn=<AddmmBackward0>)

In [33]:
t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c).unsqueeze(1) # 11x1
t_u = torch.tensor(t_u).unsqueeze(1) # 11x1
t_u.shape

torch.Size([11, 1])

In [42]:
linear_model = nn.Linear(1, 1)
optimizer = optim.SGD(
    linear_model.parameters(),
    lr=1e-2
)

In [43]:
list(linear_model.parameters())

[Parameter containing:
 tensor([[-0.3779]], requires_grad=True),
 Parameter containing:
 tensor([-0.1913], requires_grad=True)]

定义一个训练函数：

In [44]:
def training_loop(n_epochs, optimizer, model, loss_fn, t_u_train, t_u_val, t_c_train, t_c_val):
    for epoch in range(1, n_epochs + 1):
        t_p_train = model(t_u_train)
        loss_train = loss_fn(t_p_train, t_c_train)
        
        t_p_val = model(t_u_val)
        loss_val = loss_fn(t_p_val, t_c_val)
        
        optimizer.zero_grad() # 为什么要清零梯度？ 因为pytorch会累加梯度，所以每次都要清零
        loss_train.backward()
        optimizer.step() # 更新参数
        
        if epoch == 1 or epoch % 1000 == 0:
            print(f"Epoch {epoch}, Training loss {loss_train}, Validation loss {loss_val}")

In [45]:
training_loop(
    n_epochs = 3000,
    optimizer = optimizer,
    model = linear_model,
    loss_fn = nn.MSELoss(),
    t_u_train = t_u,
    t_u_val = t_u,
    t_c_train = t_c,
    t_c_val = t_c
)

print(linear_model.weight)
print(linear_model.bias)

Epoch 1, Training loss 1134.375, Validation loss 1134.375
Epoch 1000, Training loss nan, Validation loss nan
Epoch 2000, Training loss nan, Validation loss nan
Epoch 3000, Training loss nan, Validation loss nan
Parameter containing:
tensor([[nan]], requires_grad=True)
Parameter containing:
tensor([nan], requires_grad=True)


### 5.3 最终完成一个神经网络